sudo: false
language: node_js
node_js: stable
script:
- npm run deploy
cache:
  directories:
  - elm-stuff/build-artifacts
env:
  global:
    secure: Ry4byyZbXqK3Aj29i+hrAUbYiqZ1GCM7n6zAG0XIzmteNz0fYz388gee0QRGeZkF3h/OaNW2xIDVBI8OPHP5Z8tFrFw+gy6rkyMCMkyG7c5ixQ72J+oL6KiRHXQuwrax/2m0gsHRxm0Lmoms7Ukj8c+2Zj8zd85sAkp9A4nKPxkuTK/YMqz9TXMVKqRIsG2bXLV5j9bekjH1Ige9/wnohW7n7/G8yAzEzO6qQGneB4UAEzpVRhLeMgYXFRKzjTOJHyL2fyeMAp67PuHvFnqFS3R/fZqJwq4+c9OuxrfcDJkY3YHTg7apBrs2xIoJwUqeVJidaAQHGFx/A6rQ6oQS9jxcHSSL4CxLR0yOV1bY211+lq5mvEn/xCdm8p+FmoE9e2EzFCGZazB92j2yLZYuwFnWB4Y7y2SxQ9oy4ggYZGdBXBT7ZD+4qbT2d31DfuoPo+8vdUnTI9FeT8XL4DtVrMlvRYeBWPpY3EU8r7TxSKbkh8n9VDtscBEPiLMXVhPOni4IQNEaFVG/wnG9TxTpRwAg2j4REY52j6m3C2PBlUPUrpBnMj/Y4C0Qt3Yb7EpieUe9BH9PpjwXyfPt7a2gJTJ/SzWB+/7e52tUQf2Nv/4aZJvpn/Z7q1QVbHcEzS6EA10VjW66ExjxDtCMiP/NXYnjBNNKAoMrkSnCfkZWNSA=
