sudo: false
language: node_js
node_js: stable
before_script:
  - git config --global user.name '${GIT_NAME}'
  - git config --global user.email '${GIT_NAME}'
script:
  - npm run deploy
cache:
  directories:
    - elm-stuff/build-artifacts
env:
  global:
    - GITHUB_REPO: "genthaler/elm-maze-war"
    - secure: Om/dekwneQJgiaclxxCilQBLuILy0I1S4cBeZimx6/94e8kZnVHgiYSPOkZ5VWtqc2nx35/DmyfIBmdLQvM+6qtc0lbO3OQ9+YL64QxCmCnhVVRJrAPHECftesfifvf0MnG0g4i9C/7pz+znqFivtltA1JBC5q1POM0/b3KDejhp3HVoZPWiOwaho/UdGn/loQUiIB5g4qunur85HhgKQeU3285Yx9Yt0ycKXGJLmtBUlCe2bhI8sFekQjH3Nq9UVGtRiyuUTcKY7Et8uH7RVRn2+GsTuyNGkt3Krl//BfTTRTTk/i4MyxQUfEvFVDB4GWzxvSmggoe2EEM5jIEubsglK6CQAnTTTfB7CkxuZheFcvgJxG7nT1kqApe457drjITY8Fm7bJA1wMBpEGA1GIKlhmcnTgJpvzH2xQwaVJYOT/xRWx9RXeD8DEqA6MiWG2RYqyblRkLCcbfekC3NSr4nKQZzBAZJo5XiYQn7aftK2BvxDcTW/qdVG4gIJwnVZ2vrbs+cwrknA7CADRIR74N0xcFPkylWIJ3PYkVTAH445Sj1Knf9PG145T00NCdW5YT5ELv/byFGQs9XcM07Hi8FbCTqIVhMOxusiuC+ckeRtdjj8aqHoaq1CzB2YcYmFDlS2rSKWRTBuTjVkSwOjEu4u0ul6HP1pVxWiTF7SDg=
